=== Mtdung290504/BangBang-Lite/assets/jsons/tank_manifests/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "assets-manifest": {
            "type": "string",
            "pattern": "^/assets/jsons/assets_manifests/[\\w\\d_/-]+\\.json$"
        },
        "skill-manifest": {
            "type": "string",
            "pattern": "^/assets/jsons/skill_manifests/[\\w\\d_/-]+\\.json$"
        },
        "stat-components": {
            "type": "object",
            "properties": {
                "shooting": {
                    "type": "object",
                    "properties": {
                        "fireRate": {
                            "type": "number",
                            "enum": [
                                60,
                                90,
                                120
                            ]
                        },
                        "range": {
                            "type": "number",
                            "enum": [
                                336,
                                408,
                                480,
                                552
                            ]
                        },
                        "flightSpeed": {
                            "type": "number",
                            "enum": [
                                10,
                                13
                            ]
                        }
                    },
                    "required": [
                        "fireRate",
                        "range",
                        "flightSpeed"
                    ]
                },
                "survival": {
                    "type": "object",
                    "properties": {
                        "limitHP": {
                            "type": "number",
                            "minimum": 1
                        },
                        "armor": {
                            "type": "number",
                            "minimum": 0
                        },
                        "shield": {
                            "type": "number",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "limitHP",
                        "armor",
                        "shield"
                    ]
                },
                "attack-power": {
                    "type": "object",
                    "properties": {
                        "dmgType": {
                            "type": "string",
                            "enum": [
                                "physics",
                                "energy"
                            ]
                        },
                        "value": {
                            "type": "number",
                            "minimum": 0
                        },
                        "penetration": {
                            "type": "number",
                            "minimum": 0
                        },
                        "critDmg": {
                            "type": "number",
                            "enum": [
                                150,
                                200
                            ]
                        }
                    },
                    "required": [
                        "dmgType",
                        "value",
                        "penetration",
                        "critDmg"
                    ]
                },
                "additional": {
                    "type": "object",
                    "properties": {
                        "energyPoint": {
                            "type": "number",
                            "enum": [
                                100,
                                150
                            ]
                        }
                    },
                    "required": [
                        "energyPoint"
                    ]
                },
                "movement-speed": {
                    "type": "number",
                    "minimum": 150,
                    "maximum": 190
                }
            },
            "required": [
                "shooting",
                "survival",
                "attack-power"
            ]
        }
    },
    "required": [
        "name",
        "assets-manifest",
        "skill-manifest",
        "stat-components"
    ]
}

=== Mtdung290504/BangBang-Lite/assets/jsons/tank_manifests/000.json
{
    "$schema": "./schema.json",
    "name": "Admin",
    "assets-manifest": "/assets/jsons/assets_manifests/000.json",
    "skill-manifest": "/assets/jsons/skill_manifests/000.json",
    "stat-components": {
        "shooting": {
            "fireRate": 120,
            "range": 480,
            "flightSpeed": 13
        },
        "survival": {
            "limitHP": 4840,
            "armor": 138,
            "shield": 108
        },
        "attack-power": {
            "dmgType": "physics",
            "value": 306,
            "penetration": 26,
            "critDmg": 200
        },
        "movement-speed": 180
    }
}
